-- AlterTable
ALTER TABLE "Title" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "WatchEntry" ALTER COLUMN "id" DROP DEFAULT;
